services:
  mysql:
    image: mysql:8.0
    container_name: mysql-crud
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crudsystem
      MYSQL_USER: myuser
      MYSQL_PASSWORD: Password123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
